# Generated by Django 5.2.5 on 2025-09-13 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanrequest',
            old_name='created_at',
            new_name='application_date',
        ),
        migrations.RenameField(
            model_name='loanrequest',
            old_name='reason',
            new_name='purpose',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal Loan'), ('auto', 'Auto Loan'), ('home', 'Home Loan'), ('education', 'Education Loan')], default='auto', max_length=20),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='term_months',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('credit_score', models.IntegerField(default=650)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
